[project]
name = "ppo-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.5.0",
    "torch>=2.9.1",
    "transformers>=4.57.6",
    "trl>=0.27.1",
    "wandb>=0.24.0",
]
